export const GET_CARS_LOADING = 'GET_CARS_LOADING';
export const GET_CARS_SUCCESS = 'GET_CARS_SUCCESS';
export const GET_CARS_FAILURE = 'GET_CARS_FAILURE';
export const GET_CAR_DETAILS_LOADING = 'GET_CAR_DETAILS_LOADING';
export const GET_CAR_DETAILS_SUCCESS = 'GET_CAR_DETAILS_SUCCESS';
export const GET_CAR_DETAILS_FAILURE = 'GET_CAR_DETAILS_FAILURE';
export const CLEAR_CAR_DETAILS = 'CLEAR_CAR_DETAILS';
